<h1 style="color:Blue;" align=center><font size = 5>The Battle of Neighborhoods Week 1</font></h1>

<h2 style="color:Blue;">1.  Introduction</h2>

For long, tourism has been prohibitively expensive for many. Today, it has become a way of life, especially for Millenials.  Tourism comprises the activities of persons traveling to places and spending time outside their normal daily environment for leisure, business, and other purposes.  Travel exposes one to life outside; gives confidence in dealing with change and provides independence and freedom. It boosts our self-awareness and helps us get real-life education. Travel to a foreign country helps us understand foreign culture, their history, meet new people, make new friends, and helps us navigate difficult situations.

Globalization, as well as diplomatic relations among countries, has made traveling increasingly easy.  As a philomath and a historian, I acknowledge that tourism plays a prominent role for a globetrotter and, in fact for any traveler.

Tourism in India has significant potential considering the rich cultural and historical heritage, variety in ecology, terrains and places of natural beauty spread across the country. 

Constituting a major part of Deccan plateau, which is south of India, Telangana has a pleasing climate, with abundant natural and water resources.  Telangana is a highly developed state and society with proud history and grand heritage.

Telangana apart from the historical perspective of various dynastic and regional and cultural influences offers its visitors a plethora of places of pristine natural beauty. With serene lakes, verdant woods, rocky regions, abundant wildlife, flora and fauna, elaborately carved temples, magnificent palaces and forts reflecting architectural blends of Hindu, Pathan and Persian styles. The artistic temper of the local people finds expression in the varied art forms of the different tribes and regions of Telangana in paintings, handicrafts in wood and metal and textile of International repute.

Hyderabad is famous as the former seat of the fabulously wealthy Nizams. Built on the banks of the river Musi, and surrounded by huge prehistoric rock formations like petrified, grey elephants, Hyderabad is a blend of the fairy tale and earthy, a potpourri of old and new.  Endearingly called the Pearl City, it offers a variety of tourist attractions ranging from Heritage monuments, Lakes, Parks, Gardens, Resorts, Museums to delectable cuisine and a delightful shopping experience.  Hyderabad is an important center of Islamic culture, places which reflects that culture are FALAKNUMA PALACE-Dazzling beauty and sophisticated magnificence that surpasses your wildest imagination, and CHARMINAR-An example of unpatrolled artistic brilliance.

Warangal is the second largest city in Telangana.  Originally known as Orugallu which means ‘one stone’, Warangal was ruled by the Kakatiya dynasty. It is believed that the entire town was carved out on a single rock. The Kakatiyas built many monuments in the state which include iconic fortresses, gateways and temples. Among the most famous monuments of Telangana, the Thousand Pillar Temple in Hanamkonda, was built by the Kakatiya King Rudra Deva in 1163 AD in Chalukyan style of temple architecture. The city of Warangal was also described in detail by Marco Polo during his visit to the country.  The city is a cluster of three towns and is popular for many attractions. While visiting Warangal, one should definitely stop by the beautiful Khush Mahal located near the Warangal Fort, the symbol of a glorious past.

Other prominent art works of the state include Nizamabad panels, Nirmal painted furniture, Dokra castings, Silver Filigree, Cheriyal Scroll Paintings, Bidri craft, Pembarthi brassware etc.

<h2 style="color:Blue;">2.  Importance of Tourism</h2>

The tourism industry is important for the benefits it brings and due to its role as a commercial activity that creates demand and growth for many more industries. 

* Tourism boosts the revenue of the economy.  Total contribution by travel and tourism sector to India's GDP is expected to increase from Rs 15.24 lakh crore in 2017 to Rs 32.05 lakh crore in 2028. This is huge earning to India and creates thousands of jobs.
* Tourism is a significant source of foreign exchange for the country.
* Tourism develops the infrastructures of a country, and plants a sense of cultural exchange between foreigners and citizens.
* In FY20, 39 million jobs were created in the tourism sector in India; this accounted for 8.0% of the total employment in the country. The number is expected to rise by two% annum to 52.3 million jobs by 2028.
* Telangana, a state in India is steadily becoming favourite destinations for foreign tourists.  As per statistics shared by the Telangana tourism department, there is a 76% jump in foreign tourist count in 2017.

<h2 style="color:Blue;">3.  Description of the Business Problem</h2>

The objective of this project is to analyze the tourist places of Telangana state in India and recommend the best location where one can open a Restaurant or Lodging to make the best use of the opportunity.
The target audience for this project include people who are interested in opening a Restaurant, Lodging/Hotel/Motel, Transport Services or any other similar businesses which fall within the tourism industry

<h2 style="color:Blue;">4.  Data Collection & Anatomization</h2>

To find solution to the business problem mentioned above, we should have the dataset that contains

*  All the states of a particular country, India in this case,  and which has 36 states
*  Latitude and longitudes of all the districts of individual states, a total of 739 districts in India
*  Telangana state is chosen for this problem and the state has 13 districts


##### **_4.1 Source_** 

<font size = 2>The Wikipedia page https://en.wikipedia.org/wiki/List_of_districts_in_India is the major source of data that is being used to obtain all the districts of India. We then use beautifulsoup4 package, a Python module that helps to scrape information from the web pages to extract all the tables from this Wikipedia page and convert it into a pandas dataframe. Then we use Python’s geopy package to obtain the latitude and longitude of all the districts present in the dataframe. Also used Google Places API to get latitude, longitude for some locations. </font>

##### **_4.2 Description of the data_**

<font size = 2>The output shows the final dataset. The dataset consists of a single Dataframe with 9 columns containing state, districts, latitude and longitudes of the particular district etc. Other columns like code, headquarters, population, area and density have also been scraped from the website which can be used for further analysis. </font>

In [14]:
import pandas as pd
df = pd.read_excel('Capstone_TelanganaDataSet.xlsx')
df.head(15)  # Display first 15 rows

,State,Code,District,Headquarters,Population(2011),Area(km2),Density(/km2),Latitude,Longitude
0,Andaman and Nicobar,NI,Nicobar,Car Nicobar,36842,1841.00,20.0,7,93
1,Andaman and Nicobar,NaN,North and Middle Andaman,Mayabunder,105597,3736.00,28.0,12.6112,92.8317
2,Andaman and Nicobar,SA,South Andaman,Port Blair,238142,2672.00,89.0,10.7057,92.4875
3,Andhra Pradesh,AN,Anantapur,Anantapur,4083315,19130.00,213.0,14.6546,77.5563
4,Andhra Pradesh,CH,Chittoor,Chittoor,4170468,15152.00,275.0,13.1601,79.1556
5,Andhra Pradesh,EG,East Godavari,Kakinada,5151549,10807.00,477.0,17.2335,81.7226
6,Karnataka,BK,Bagalkot,Bagalkot,1890826,6583.00,288.0,16.1853,75.6968
7,Karnataka,BL,Ballari,Ballari,2532383,8439.00,300.0,15.2485,76.8324
8,Karnataka,BG,Belgaum,Belgaum,4778439,13415.00,356.0,15.8573,74.5069
9,Karnataka,BR,Bangalore Rural,Bangalore,987257,2239.00,441.0,13.0011,77.3361
10,Karnataka,BN,Bangalore Urban,Bangalore,9588910,2190.00,4378.0,12.9451,77.5536
11,Telangana,AD,Adilabad,Adilabad,708952,4185.97,171.0,19.6641,78.532
12,Telangana,KB,Komaram Bheem,Asifabad,515835,4300.16,106.0,19.3619,79.293
13,Telangana,BK,Bhadradri Kothagudem,Kothagudem,1304811,8951.00,143.0,17.556,80.617
14,Telangana,HY,Hyderabad,Hyderabad,3441992,4325.29,18172.0,17.385,78.4867

##### **_4.3 How Data will be used to solve the problem_**

*  Get geograpical co-ordinates of Telangana State
*  Create dataframe containing the districts of the state
*  Retrieve the required main and sub categories present in Foursquare API - Arts & Entertainment, Nightlife Spot, Outdoors & Recreation, Food, Shop & Service and Travel & Transport
*  Get nearby venues of all the districts in Telangana State and analyze each district
*  Get most common venues according to the venue category in each district
*  Identify top 10 businesses
*  Find the optimal k value for clustering, Perform Clustering and Visualize Clusters
*  Examine each cluster and determine the businesses that distinguish each cluster.